_core:
  default_config_hash: LcC8V80ozYD62aCxkODOw1dBN9x7g4AXqMOrQYYvBt0
data_source_url: 'https://raw.githubusercontent.com/NISRA-Tech-Lab/latest-publications/refs/heads/main/nisra_release_calendar.json'
data_source_url_historic: 'https://raw.githubusercontent.com/NISRA-Tech-Lab/latest-publications/refs/heads/main/nisra_release_historic.json'
