_core:
  default_config_hash: gtwzO2VwZJpMr2idLTwcgyVi_k1vrDcb989pvSiRmNw
data_source_url: raw.githubusercontent.com/NISRA-Tech-Lab/latest-publications/refs/heads/b-org/nisra_release_calendar.json
data_source_url_historic: raw.githubusercontent.com/NISRA-Tech-Lab/latest-publications/refs/heads/b-org/nisra_release_historic.json
